spring:
  # H2 DB 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  # H2 DB 방언 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
